  command = "CI=false npm run build"
  publish = "build"
  
# Handle SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
  REACT_APP_API_URL = "https://api.mindcloud.app"