[build]
  base = "frontend/"
  publish = "build/"
  command = "CI=false npm run build"

# Environment variables that should be available during build
[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  REACT_APP_API_URL = "http://grey-mongoose-prod.eba-asi6kjji.us-west-2.elasticbeanstalk.com:8081"

# Proxy API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "http://grey-mongoose-prod.eba-asi6kjji.us-west-2.elasticbeanstalk.com:8081/api/:splat"
  status = 200
  force = true

# Redirect all other routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
